[package]
name = "usd1ball"
version = "0.1.0"
description = "USD1BALL - A USD1-based flywheel meme coin"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "usd1ball"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
solana-program = "~1.17"

[dev-dependencies]
solana-program-test = "~1.17"
solana-sdk = "~1.17"
spl-token = "4.0"
